name: wear_example
description: Demonstrates how to use the wear plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  wear:
    path: ../
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
