name: wear
description: A plugin that offers widgets for Wear OS by Google
version: 0.0.3
author: Matt Sullivan <matt.j.sullivan@gmail.com>
homepage: https://github.com/mjohnsullivan/flutter_wear_plugin

environment:
  sdk:  ">=2.0.0-dev.68.0 <3.0.0"
  flutter: ">=0.11.12 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.1.6

flutter:
  plugin:
    androidPackage: com.mjohnsullivan.flutterwear.wear
    pluginClass: WearPlugin
