name: wear
description: A plugin that offers Flutter support for Wear OS by Google
version: 0.1.0
homepage: https://github.com/fluttercommunity/flutter_wear_plugin

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  meta: ^1.1.8
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.mjohnsullivan.flutterwear.wear
        pluginClass: WearPlugin
